#!/usr/bin/env python
import time, RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(4, GPIO.IN)

light = True

while 1:
        i = GPIO.input(4)
        if i:
                GPIO.output(17, GPIO.HIGH)
        GPIO.output(17, GPIO.LOW)
